Add support for command line options
scoliono/archiveripper pull request #2
Opened 2021-01-06 00:19 UTC by notevenaperson

Makes it easy to call the script in an non-interactive environment (i.e. a script).

2021-02-15 08:32 UTC, scoliono requested changes
Nice work, there's just a couple small changes I would like before I merge this in,

2021-02-15 08:32 UTC, scoliono commented on api.py
> +    def download_page(self, i, scale="0"):
The scale parameter makes more sense as an integer. Then you just need to change `%s` to `%d` in the format string below.

2021-02-15 08:32 UTC, scoliono commented on ripper.py
> +            desired_pages = args.page_range
This is a good start, but it would be even better if the start and end page numbers were separate parameters. Then, it would go from page X to the end (or from the beginning to page Y) if you only provided one.

2021-02-17 15:15 UTC, notevenaperson commented on ripper.py
> +            desired_pages = args.page_range
I only made the --page-range option like I did to re-use the code that was already there, the code that asked for the page range interactively. As you wished, it's now split into two options without an increasing line count, which I initially didn't think I could write. Please review my new commit.

2021-09-12 13:52 UTC, notevenaperson commented
@scoliono Would you please review my changes

2021-09-12 23:28 UTC, merged

2021-09-12 23:29 UTC, scoliono commented
Sorry for the late response. I could have sworn I came back for code review at some point and your account had totally vanished.

Just fixed a couple small things and merged.

2021-09-13 20:03 UTC, notevenaperson commented
You didn't imagine things, indeed my account was banned for a few weeks until I appealed.